dj/dj/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import index


urlpatterns = [
    path('', index),
    path('', include('tvk.urls', namespace='tvk')),
    path('user/', include('users.urls', namespace='user')),
    path('report/', include('report.urls', namespace='report')),
    path('admin/', admin.site.urls),
]

dj/report/urls.py
from django.urls import path
from . import views

app_name = 'report'

urlpatterns = [
    path('choose_period', views.choose_period, name='choose_period'),
    path('report', views.report, name='report'),
    path('contraventions', views.contraventions, name='contraventions'),
    path('contraventions/<int:page>', views.contraventions,
         name='p_contraventions'),
    path('checking', views.checking, name='checking'),
    path('checking/<int:page>', views.checking, name='p_checking'),
]

dj/tvk/urls.py
from django.urls import path
from . import views

app_name = 'tvk'

urlpatterns = [
    path('main', views.main, name='main'),
    path('main/<int:page>', views.main, name='p_main'),
    path('cic', views.cic, name='cic'),
    path('cic/<int:id>', views.cic, name='edit_cic'),
    path('save_cic', views.save_cic, name='save_cic'),
    path('view_cic/<int:id>', views.view_cic, name='view_cic'),
    path('delete_cic/<int:id>', views.delete_cic, name='delete_cic'),
    path('department', views.department, name='department'),
    path('department/<int:id>', views.department, name='edit_department'),
    path('save_department', views.save_department, name='save_department'),
    path('delete_department/<int:id>', views.delete_department,
         name='delete_department'),
    path('risk', views.risk, name='risk'),
    path('risk/<int:id>', views.risk, name='edit_risk'),
    path('save_risk', views.save_risk, name='save_risk'),
    path('upload_file', views.upload_file, name='upload_file'),
    path('delete_risk/<int:id>', views.delete_risk, name='delete_risk'),
    path('imns', views.imns, name='imns'),
    path('imns/<int:id>', views.imns, name='edit_imns'),
    path('save_imns', views.save_imns, name='save_imns'),
    path('delete_imns/<int:id>', views.delete_imns, name='delete_imns'),
    path('exam<int:cic>', views.exam, name='exam'),
    path('exam<int:cic>/<int:id>', views.exam, name='edit_exam'),
    path('save_exam', views.save_exam, name='save_exam'),
    path('delete_exam/<int:id>', views.delete_exam, name='delete_exam'),
]

dj/report/models.py
#from django.db import models

# Create your models here.

dj/report/forms.py
from django import forms
from datetime import datetime
from tvk.models import Imns, Risk, Department


class ChoosePeriodForm(forms.Form):
    date_from = forms.DateField(label='Период с', required=False, initial=None,
                                widget=forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}))
    date_to = forms.DateField(label='Период по', required=False, initial=None,
                              widget=forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}))


class FilterForm(forms.Form):
    subject = forms.ModelChoiceField(label='Субъект', queryset=Imns.objects.order_by('number'),
                                     widget=forms.Select(attrs={
                                        'onchange': "this.form.submit()"
                                     }), required=False)
    obj = forms.ModelChoiceField(label='Объект', queryset=Imns.objects.order_by('number').exclude(number=300),
                                 widget=forms.Select(attrs={
                                    'onchange': "this.form.submit()"
                                 }), required=False)
    risk = forms.ModelChoiceField(label='Риск',
                                  queryset=Risk.objects.order_by('code').exclude(enable=False),
                                  widget=forms.Select(attrs={
                                    'onchange': "this.form.submit()"
                                  }), required=False)
    department = forms.ModelChoiceField(label='Подразделение',
                                        queryset=Department.objects.all(),
                                        widget=forms.Select(attrs={
                                            'onchange': "this.form.submit()"
                                        }), required=False)
    year = forms.ChoiceField(label='год', widget=forms.Select(attrs={
                                'onchange': "this.form.submit()"
                            }), required=False,
                            choices=[('', '----')]+[(year, year) for year in range(datetime.now().year, 2021, -1)])


class CheckingFilterForm(forms.Form):
    subject = forms.ModelChoiceField(label='Субъект', queryset=Imns.objects.order_by('number'),
                                     widget=forms.Select(attrs={
                                        'onchange': "this.form.submit()"
                                     }), required=False)
    risk = forms.ModelChoiceField(label='Риск',
                                  queryset=Risk.objects.order_by('code').exclude(enable=False),
                                  widget=forms.Select(attrs={
                                    'onchange': "this.form.submit()"
                                  }), required=False)
    department = forms.ModelChoiceField(label='Подразделение',
                                        queryset=Department.objects.all(),
                                        widget=forms.Select(attrs={
                                            'onchange': "this.form.submit()"
                                        }), required=False)
    year = forms.ChoiceField(label='год', widget=forms.Select(attrs={
                                'onchange': "this.form.submit()"
                            }), required=False,
                            choices=[('', '----')]+[(year, year) for year in range(datetime.now().year, 2021, -1)])

dj/report/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Sum
from django.conf import settings
from .forms import ChoosePeriodForm, FilterForm, CheckingFilterForm
from tvk.models import Department, Imns, CIC, Examination, Risk
import csv
import os


# Create your views here.
@login_required
def choose_period(request: HttpRequest):
    """chose period"""
    choose_form = ChoosePeriodForm()

    context = {'form': choose_form}
    return render(request, 'report/choose_period.html', context=context)


@login_required
def report(request: HttpRequest):
    """report"""
    if 'raion' in request.POST:
        return report_function(request, subj_raion=True)
    elif '300' in request.POST:
        return report_function(request, subj_300=True)
    elif 'file' in request.POST:
        return unload_csv(request)
    else:
        return report_function(request)


def unload_csv(request: HttpRequest):
    user = request.user

    if user.access != 1 and user.access != 3 and user.access != 5:
        b_cic = CIC.objects.filter(imnss=user.imns)
    else:
        b_cic = CIC.objects.all()

    date_from = request.POST.get('date_from', None)
    date_to = request.POST.get('date_to', None)

    if date_from:
        b_cic = b_cic.filter(date_state__gte=date_from)
    if date_to:
        b_cic = b_cic.filter(date_state__lte=date_to)

    header = ['Субъект', 'Объект', '№ отчета', 'Дата утверждения', 'Дата с',
              'Дата по', 'Риск', 'Название риска', 'Документы', 'Нарушений',
              'Краткая суть', 'Управление', 'ФИО']
    with open(user.username + '.csv', mode='w', encoding='utf-8-sig') as file:
        writer = csv.writer(file, delimiter=';')
        writer.writerow(header)

        for i_cic in b_cic:
            exam = Examination.objects.filter(cic=i_cic)
            for i_exam in exam:
                line = []
                line.append(i_cic.imnss.number)
                line.append(i_exam.obj.number)
                line.append(i_cic.number)
                line.append(i_cic.date_state)
                line.append(i_cic.date_from)
                line.append(i_cic.date_to)
                line.append(i_exam.risk.code)
                line.append(i_exam.risk.name)
                line.append(i_exam.count_all)
                line.append(i_exam.count_contravention)
                line.append(i_exam.description)
                line.append(i_exam.department.name)
                line.append(i_exam.fio)
                writer.writerow(line)

    """unload file"""
    file_path = os.path.join(settings.MEDIA_ROOT, user.username + '.csv')
    if os.path.exists(file_path):
        with open(file_path, mode='rb') as fh:
            response = HttpResponse(fh.read(),
                                    content_type="application/vnd.ms-excel")
            response['Content-Disposition'] = 'inline; filename=' + \
                os.path.basename(file_path)
            return response
    else:
        return redirect('tvk:main')


def report_function(request: HttpRequest, subj_300=False, subj_raion=False):
    if request.method == 'POST':
        date_from = request.POST.get('date_from', None)
        date_to = request.POST.get('date_to', None)
        departments = Department.objects.all()
        imns = Imns.objects.order_by('number').exclude(number=300)

        rez = []
        count = 1
        for i_imns in imns:
            buf_rez = []
            buf_rez.append(str(count))
            buf_rez.append(str(i_imns.shot_name))
            buf_rez.append(str(i_imns.number))

            b_cic = CIC.objects.all()
            if date_from:
                b_cic = b_cic.filter(date_state__gte=date_from)
            if date_to:
                b_cic = b_cic.filter(date_state__lte=date_to)
            if subj_300:
                b_cic = b_cic.filter(imnss=Imns.objects.get(number=300))
            if subj_raion:
                b_cic = b_cic.exclude(imnss=Imns.objects.get(number=300))

            rez_dep = []
            exam = Examination.objects.filter(obj=i_imns, cic__in=b_cic).exclude(count_contravention=0)
            c1 = 0
            c2 = 0
            for i_dep in departments:

                dep_filt = exam.filter(department=i_dep)
                if not dep_filt or dep_filt.count == 0:
                    rez_dep.append(0)
                    rez_dep.append(0)
                    continue

                c1 = dep_filt.values('cic').distinct().count()
                c2 = dep_filt.values('risk').distinct().count()

                rez_dep.append(c1)
                rez_dep.append(c2)

            # sum1 - cont all imns, sum2 -risk all imns
            sum1 = exam.values('cic').distinct().count()
            sum2 = exam.values('risk').distinct().count()

            buf_rez.append(sum1)
            buf_rez.append(sum2)
            buf_rez.extend(rez_dep)

            rez.append(buf_rez)
            count += 1

        # итого
        buf_rez_list = []
        for i_dep in departments:
            total_cic_dep = Examination.objects.filter(cic__in=b_cic, department=i_dep).exclude(count_contravention=0).values('cic').distinct().count()
            total_risk_dep = Examination.objects.filter(cic__in=b_cic, department=i_dep).exclude(count_contravention=0).values('risk').distinct().count()
            buf_rez_list.append(total_cic_dep)
            buf_rez_list.append(total_risk_dep)

        buf_rez = []
        buf_rez.append('')
        buf_rez.append('итого')
        buf_rez.append('')
        total_cic = Examination.objects.filter(cic__in=b_cic).exclude(count_contravention=0).values('cic').distinct().count()
        buf_rez.append(total_cic)
        total_risk = Examination.objects.filter(cic__in=b_cic).exclude(count_contravention=0).values('risk').distinct().count()
        buf_rez.append(total_risk)
        buf_rez.extend(buf_rez_list)
        rez.append(buf_rez)

        context = {'department_list': departments,
                   'rezult': rez}

        return render(request, 'report/report.html', context=context)

    return redirect('tvk:main')


@login_required
def contraventions(request: HttpRequest, page: int = 1):
    """contravention"""
    user = request.user

    form = FilterForm()

    if user.access != 1 and user.access != 3 and user.access != 5:
        form.fields['obj'].queryset = Imns.objects.filter(id=user.imns.id)

    subject = ''
    obj = ''
    risk = ''
    dep = ''
    year = ''
    if "subject" in request.GET:
        form = FilterForm(data=request.GET)
        subject = form['subject'].value()
        obj = form['obj'].value()
        risk = form['risk'].value()
        dep = form['department'].value()
        year = form['year'].value()

    if subject == '':
        if year != '':
            cic = CIC.objects.filter(date_state__year=year).order_by('-id')
        else:
            cic = CIC.objects.order_by('-id')
    else:
        if year != '':
            cic = CIC.objects.filter(imnss__pk=subject, date_state__year=year).order_by('-id')
        else:
            cic = CIC.objects.filter(imnss__pk=subject).order_by('-id')

    rez = []
    for i_cic in cic:
        if user.access == 1 or user.access == 3 or user.access == 5:
            if obj == '':
                exam = Examination.objects.filter(cic=i_cic).exclude(count_contravention=0).order_by('-id')
            else:
                exam = Examination.objects.filter(cic=i_cic, obj__pk=obj).exclude(count_contravention=0).order_by('-id')
        else:
            exam = Examination.objects.filter(cic=i_cic, obj=user.imns).exclude(count_contravention=0).order_by('-id')

        if risk != '':
            exam = exam.filter(risk__pk=risk)

        if dep != '':
            exam = exam.filter(department__pk=dep)

        for i_exam in exam:
            cic_buf = {'risk': i_cic}
            cic_buf['exam'] = i_exam
            rez.append(cic_buf)

    paginator = Paginator(rez, 10)
    page_obj = paginator.get_page(page)

    context = {'page_obj': page_obj,
               'form': form}
    return render(request, 'report/contraventions.html', context=context)


@login_required
def checking(request: HttpRequest, page: int = 1):
    """checking"""
    user = request.user

    form = CheckingFilterForm()

    subject = ''
    risk = ''
    dep = ''
    year = ''
    if 'subject' in request.GET:
        form = CheckingFilterForm(data=request.GET)
        subject = form['subject'].value()
        risk = form['risk'].value()
        dep = form['department'].value()
        year = form['year'].value()

    if subject == '':
        if year != '':
            cic = CIC.objects.filter(date_state__year=year).order_by('-pk')
        else:
            cic = CIC.objects.order_by('-pk')
    else:
        if year != '':
            cic = CIC.objects.filter(imnss__pk=subject, date_state__year=year).order_by('-pk')
        else:
            cic = CIC.objects.filter(imnss__pk=subject).order_by('-pk')

    rez = []
    for i_cic in cic:
        if user.access == 1 or user.access == 3 or user.access == 5:
            if dep != '':
                exam = Examination.objects.filter(cic=i_cic, department__pk=dep)
            else:
                exam = Examination.objects.filter(cic=i_cic)
        else:
            if dep != '':
                exam = Examination.objects.filter(cic=i_cic, obj=user.imns, department__pk=dep)
            else:
                exam = Examination.objects.filter(cic=i_cic, obj=user.imns)

        if risk != '':
            exam = exam.filter(risk__pk=risk)

        if exam.count() == 0:
            continue

        sum_all = exam.aggregate(Sum('count_all'))
        sum_cont = exam.aggregate(Sum('count_contravention'))
        cic_buf = {'risk': i_cic}
        risk_list = exam.values('risk').distinct()

dj/report/templates/report/checking.html
{%extends 'tvk/base_generic.html' %}

{% block content %}
    <div class='container-fluid'>
        <div class='row'>
            <form action="{% url 'report:checking'%}" method='GET'>
                {% csrf_token %}
                {{form}}
            </form>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-bordered w-auto">
                <thead>
                    <th>№</th>
                    <th>Субъект</th>
                    <th>Объект</th>
                    <th>№ отчета</th>
                    <th>Обзорное письмо</th>
                    <th>Дата</th>
                    <th>С-по</th>
                    <th>Риск</th>
                    <th>Всего документов</th>
                    <th>Всего нарушений</th>
                    <th>Управление</th>
                    <th></th>
                </thead>
                <tbody>
                    {% for i_rez in page_obj %}
                        <tr>
                            <td>{{i_rez.risk.id}}</td>
                            <td>{{i_rez.risk.imnss.number}}</td>
                            <td>
                                {% for i_imns in i_rez.imns_list %}
                                    {{i_imns.number}}; 
                                {% endfor %}
                            </td>
                            <td>{{i_rez.risk.number}}</td>
                            <td>{{i_rez.risk.message}}</td>
                            <td>{{i_rez.risk.date_state|date:'d.m.Y'}}</td>
                            <td>{{i_rez.risk.date_from|date:'d.m.Y'}} - {{i_rez.risk.date_to|date:'d.m.Y'}}</td>
                            <td>
                                {% for i_risk in i_rez.risk_list %}
                                    {{i_risk.code}}; 
                                {% endfor %}
                            </td>
                            <td>{{i_rez.sum_all}}</td>
                            <td>{{i_rez.sum_cont}}</td>
                            <td>{% for i_dep in i_rez.dep_list %}{{i_dep.name}}; {%endfor%}</td>
                            <td><a href="{%url 'tvk:view_cic' id=i_rez.risk.id%}">🔎</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        {% block paginator %}
            <div class='pagination'>
                <span class='page-links'>
                    {% if page_obj.has_previous %}
                        <a href="{% url 'report:p_checking' page=page_obj.previous_page_number%}">Предыдущая</a>
                        {% endif %}
                        <span class="page-current">
                            Страница {{page_obj.number}} из {{page_obj.paginator.num_pages}}.
                        </span>
                        {% if page_obj.has_next%}
                        <a href="{% url 'report:p_checking' page=page_obj.next_page_number%}">Следующая</a>
                    {% endif %}
                    {% for page_number in page_obj.paginator.page_range %}
                        <a
                            href="{% url 'report:p_checking' page=page_number%}"
                            class="{% if page_number == page_obj.number %}current{% endif %}"
                        >
                            {{page_number}}
                        </a>
                    {% endfor %}
                </span>
            </div>
        {% endblock %}

    </div>
{% endblock %}

dj/report/templates/report/choose_period.html
{% extends 'tvk/base_generic.html' %}

{% block content %}
    <div class='container'>
        <form action="{% url 'report:report' %}" method='POST'>
            {% csrf_token %}
            <table>
                {{form.as_table}}
            </table>
            <input type='submit' name='all' value='Сформировать для всех' />
            <input type='submit' name='300' value='Сформировать для области' />
            <input type='submit' name='raion' value='Сформировать для районов' />
            <input type='submit' name='file' value='Выгрузить в эксель' />
        </form>
    </div>
{% endblock %}

dj/report/templates/report/contraventions.html
{%extends 'tvk/base_generic.html' %}

{% block content %}
    <div class='container-fluid'>
        <div class='row'>
            <form action="{% url 'report:contraventions'%}" method='GET' name='contr_form'>
                {% csrf_token %}
                {{form}}
            </form>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-bordered w-auto">
                <thead>
                    <th>№</th>
                    <th>Субъект</th>
                    <th>Объект</th>
                    <th>№ отчета</th>
                    <th>Обзорное письмо</th>
                    <th>Дата</th>
                    <th>С-по</th>
                    <th>Риск</th>
                    <th>Документов</th>
                    <th>Нарушений</th>
                    <th>Краткая суть</th>
                    <th>Управление</th>
                    <th>ФИО</th>
                    <th></th>
                </thead>
                <tbody>
                    {% for i_rez in page_obj %}
                        <tr>
                            <td>{{i_rez.risk.id}}</td>
                            <td>{{i_rez.risk.imnss.number}}</td>
                            <td>{{i_rez.exam.obj.number}}</td>
                            <td>{{i_rez.risk.number}}</td>
                            <td>{{i_rez.risk.message}}</td>
                            <td>{{i_rez.risk.date_state|date:'d.m.Y'}}</td>
                            <td>{{i_rez.risk.date_from|date:'d.m.Y'}} - {{i_rez.risk.date_to|date:'d.m.Y'}}</td>
                            <td title='{{i_rez.exam.risk.name}}'>{{i_rez.exam.risk.code}}</td>
                            <td>{{i_rez.exam.count_all}}</td>
                            <td>{{i_rez.exam.count_contravention}}</td>
                            <td>{{i_rez.exam.description}}</td>
                            <td>{{i_rez.exam.department.name}}</td>
                            <td>{{i_rez.exam.fio}}</td>
                            <td><a href="{%url 'tvk:view_cic' id=i_rez.risk.id%}">🔎</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        {% block paginator %}
            <div class='pagination'>
                <span class='page-links'>
                    {% if page_obj.has_previous %}
                        <a href="{% url 'report:p_contraventions' page=page_obj.previous_page_number%}">Предыдущая</a>
                        {% endif %}
                        <span class="page-current">
                            Страница {{page_obj.number}} из {{page_obj.paginator.num_pages}}.
                        </span>
                        {% if page_obj.has_next%}
                        <a href="{% url 'report:p_contraventions' page=page_obj.next_page_number%}">Следующая</a>
                    {% endif %}
                    {% for page_number in page_obj.paginator.page_range %}
                        <a
                            href="{% url 'report:p_contraventions' page=page_number%}"
                            class="{% if page_number == page_obj.number %}current{% endif %}"
                        >
                            {{page_number}}
                        </a>
                    {% endfor %}
                </span>
            </div>
        {% endblock %}

    </div>
{% endblock %}

dj/report/templates/report/report.html
{% extends 'tvk/base_generic.html' %}

{% block content %}
    <div class='container-fluid'>
        <div class="table-responsive" style="overflow-x: auto">
            <table class="table table-striped table-bordered w-auto table-sm">
                <thead>
                    <tr>
                        <th rowspan="2">№</th>
                        <th rowspan="2">Наименование инспекции</th>
                        <th rowspan="2">Код инспекции</th>
                        <th rowspan="2">Количество проведенных проверок с нарушениями, итого</th>
                        <th rowspan="2">Количество проверенных рисков с нарушениями, итого</th>
                        {% for i_department in department_list %}
                            <th colspan="2">{{i_department.name}}</th>
                        {% endfor %}
                    </tr>
                    <tr>
                        {% for _ in department_list %}
                            <th>Кол-во проверок</th>
                            <th>Кол-во пров. рисков</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for i_rez in rezult %}
                        <tr>
                            {% for j_rez in i_rez %}
                                <td>{{j_rez}}</td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}