dj/dj/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import index


urlpatterns = [
    path('', index),
    path('', include('tvk.urls', namespace='tvk')),
    path('user/', include('users.urls', namespace='user')),
    path('report/', include('report.urls', namespace='report')),
    path('admin/', admin.site.urls),
]

dj/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    path('login', views.login, name='login'),
    path('users', views.users, name='users'),
    path('user/<int:id>', views.users, name='change_user'),
    path('save_user', views.save_user, name='save_user'),
    path('delete_user/<int:id>', views.delete_user, name='delete_user'),
    path('clearsession', views.clear_session, name='clearsession'),
]

dj/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .const import access
from tvk.models import Imns


# Create your models here.
class User(AbstractUser):
    access = models.IntegerField(choices=access, blank=True, null=True)
    imns = models.ForeignKey(Imns, verbose_name='Инспекция', 
                             on_delete=models.PROTECT, 
                             blank=True, null=True)

    def __str__(self):
        return str(self.username)

dj/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms
from .models import User
from .const import access
from tvk.models import Imns


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Логин',
        'class': 'form-control'
    }), label='Логин')
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Пароль'
    }), label='Пароль')

    class Meta:
        model = User
        fields = ['username', 'password']


class UserSaveForm(UserCreationForm):
    id = forms.CharField(widget=forms.HiddenInput, required=False, initial='')
    username = forms.CharField(widget=forms.TimeInput(attrs={
        'placeholder': 'Логин',
        'class': 'form-control'
    }), label='Логин')
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Пароль'
    }), label='Пароль')
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Пароль'
    }), label='Повторите пароль')
    access = forms.ChoiceField(choices=access, label='Доступ')
    imns = forms.ModelChoiceField(label='Инспекция',
                                  queryset=Imns.objects.all())

    class Meta:
        model = User
        fields = ['id', 'username', 'password1', 'password2', 'access', 'imns']

dj/users/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from .forms import UserLoginForm, UserSaveForm
from .models import User
from tvk.models import Imns
from .const import access_r


# Create your views here.
def index(request: HttpRequest):
    """index page"""
    if request.method == 'GET':
        id_user = request.session.get('id_user', None)
        if id_user:
            return redirect("tvk:main")
    context = {"form": UserLoginForm()}
    return render(request, 'users/index.html', context=context)


def login(request: HttpRequest):
    """login page"""
    if request.method == "POST":

        message = ''
        login = request.POST.get('username', None)
        password = request.POST.get('password', None)
        if not login and not password:
            message = 'Введите логин и пароль'
        else:
            user = auth.authenticate(username=login, password=password)
            if user:
                auth.login(request, user)
                return redirect('tvk:main')
            else:
                message = 'Неправильный логин или пароль'

        context = {'message': message,
                   'form': UserLoginForm()}
        return render(request, 'users/index.html', context=context)


@login_required
def users(request: HttpRequest, id: int = None):
    """users page"""
    user = request.user

    user_form = UserSaveForm()

    if id is not None:
        user_edit = User.objects.get(id=id)
        user_form = UserSaveForm(instance=user_edit)

    user_list = []
    if user.access == 1:
        user_form.fields['imns'].queryset = Imns.objects.all()
        user_list = User.objects.all()
    else:
        user_form.fields['imns'].queryset = Imns.objects.filter(id=user.imns.id)
        user_form.fields['access'].choices = access_r
        user_list = User.objects.filter(imns=user.imns)

    context = {'user': user,
               'form': user_form,
               'user_list': user_list}
    return render(request, 'users/users.html', context=context)


@login_required
def save_user(request: HttpRequest):
    """save_user page"""
    if request.method == "POST":
        id = request.POST.get('id', '')
        if id != '':
            user = User.objects.get(id=id)
            user_form = UserSaveForm(instance=user, data=request.POST)
            username = request.POST.get('username')
            pass1 = request.POST.get('password1')
            pass2 = request.POST.get('password2')
            access = request.POST.get('access')
            imns = Imns.objects.get(id=request.POST.get('imns'))
            if pass1 == pass2 and pass1 != '':
                user.username = username
                user.access = access
                user.imns = imns
                user.save()
                user.set_password(pass1)
                user.save()
                return redirect('users:users')
        else:
            user_form = UserSaveForm(data=request.POST)
        if user_form.is_valid():
            user_form.save()
        else:
            return HttpResponse('Не верно заполнена форма'
                                + str(user_form.errors))

    return redirect('users:users')


@login_required
def delete_user(request: HttpRequest, id: int = None):
    """delete_user page"""
    if request.method == "GET" and id:
        del_user = User.objects.get(id=id)
        del_user.delete()
    return redirect('users:users')


def clear_session(request: HttpRequest):
    """clear session"""
    request.session.clear()
    request.session.modified = True
    auth.logout(request)
    return redirect("users:index")

dj/users/templates/users/index.html
<!DOCTYPE html>
<html lang="ru">
    {%load static %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="TVK">
  <meta name="author" content="Anton Kralin">
  <title>TVK</title>
  <link href="{%static 'tvk/css/bootstrap.min.css'%}" rel="stylesheet">
  <style>
        .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
        }

        @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
        }

        .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
        }

        .bi {
        vertical-align: -.125em;
        fill: currentColor;
        }

        .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
        }

        .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
        }
        .bd-mode-toggle {
        z-index: 1500;
        }
  </style>
  <link href="{% static 'tvk/css/sign-in.css'%}" rel="stylesheet">
</head>

<body class="text-center">
    <main class="form-signin w-100 m-auto">
        <form method="POST" action="{% url 'users:login' %}">
            {% csrf_token %}
              <img class="mb-4" src="{%static 'tvk/img/bootstrap-logo.svg' %}" alt="" width="72" height="57">
              <h1 class="h3 mb-3 fw-normal">Пожалуйста залогиньтесь</h1>
      
              {{form.as_table}}
      
              <div class="checkbox mb-3">
              </div>
              <button class="w-100 btn btn-lg btn-primary" type="submit">Войти</button>
              <h1 class="h6 mb-6 fw-normal">{{ message }}</h1>
          </form>
    </main>

</body>

</html>

dj/users/templates/users/users.html
{% extends 'tvk/base_generic.html' %}

{% block content %}
    <div class='container-fluid'>
    <div class='row'>
        <div class='col-6'>
            <div class="table-responsive">
                <table class="table table-striped table-bordered w-auto">
                    <thead>
                        <th>Логин</th>
                        <th>Доступ</th>
                        <th>Инспекции</th>
                        <th></th>
                        <th></th>
                    </thead>
                    <tbody>
                        {% for i_user in user_list %}
                            <tr>
                                <td>{{i_user.username}}</td>
                                <td>{{i_user.access}}</td>
                                <td>{{i_user.imns.number}}</td>
                                <td><a href='{% url "users:change_user" id=i_user.id %}' >Изменить</a></td>
                                <td><a href='{% url "users:delete_user" id=i_user.id %}' >Удалить</a></td>
                            <tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <div class='col-6'>
            <form action='{%url "users:save_user" %}' method='POST'>
                {% csrf_token %}
                {{form.as_p}}
                <input type='submit' value='Сохранить' />
            </form>
        </div>
    </div>
    </div>
{% endblock %}