dj/dj/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import index


urlpatterns = [
    path('', index),
    path('', include('tvk.urls', namespace='tvk')),
    path('user/', include('users.urls', namespace='user')),
    path('report/', include('report.urls', namespace='report')),
    path('admin/', admin.site.urls),
]

dj/report/urls.py
from django.urls import path
from . import views

app_name = 'report'

urlpatterns = [
    path('choose_period', views.choose_period, name='choose_period'),
    path('report', views.report, name='report'),
    path('contraventions', views.contraventions, name='contraventions'),
    path('contraventions/<int:page>', views.contraventions,
         name='p_contraventions'),
    path('checking', views.checking, name='checking'),
    path('checking/<int:page>', views.checking, name='p_checking'),
]

dj/tvk/urls.py
from django.urls import path
from . import views

app_name = 'tvk'

urlpatterns = [
    path('main', views.main, name='main'),
    path('main/<int:page>', views.main, name='p_main'),
    path('cic', views.cic, name='cic'),
    path('cic/<int:id>', views.cic, name='edit_cic'),
    path('save_cic', views.save_cic, name='save_cic'),
    path('view_cic/<int:id>', views.view_cic, name='view_cic'),
    path('delete_cic/<int:id>', views.delete_cic, name='delete_cic'),
    path('department', views.department, name='department'),
    path('department/<int:id>', views.department, name='edit_department'),
    path('save_department', views.save_department, name='save_department'),
    path('delete_department/<int:id>', views.delete_department,
         name='delete_department'),
    path('risk', views.risk, name='risk'),
    path('risk/<int:id>', views.risk, name='edit_risk'),
    path('save_risk', views.save_risk, name='save_risk'),
    path('upload_file', views.upload_file, name='upload_file'),
    path('delete_risk/<int:id>', views.delete_risk, name='delete_risk'),
    path('imns', views.imns, name='imns'),
    path('imns/<int:id>', views.imns, name='edit_imns'),
    path('save_imns', views.save_imns, name='save_imns'),
    path('delete_imns/<int:id>', views.delete_imns, name='delete_imns'),
    path('exam<int:cic>', views.exam, name='exam'),
    path('exam<int:cic>/<int:id>', views.exam, name='edit_exam'),
    path('save_exam', views.save_exam, name='save_exam'),
    path('delete_exam/<int:id>', views.delete_exam, name='delete_exam'),
]

dj/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    path('login', views.login, name='login'),
    path('users', views.users, name='users'),
    path('user/<int:id>', views.users, name='change_user'),
    path('save_user', views.save_user, name='save_user'),
    path('delete_user/<int:id>', views.delete_user, name='delete_user'),
    path('clearsession', views.clear_session, name='clearsession'),
]

dj/tvk/models.py
from django.db import models


# Create your models here.
class Risk(models.Model):
    code = models.CharField(max_length=50, unique=True)
    name = models.TextField()
    description = models.TextField(blank=True, null=True)
    enable = models.BooleanField(default=True)

    objects = models.Manager()

    def __str__(self) -> str:
        return self.code


class Department(models.Model):
    name = models.CharField(max_length=255)
    objects = models.Manager()

    def __str__(self):
        return str(self.name)


class Imns(models.Model):
    number = models.IntegerField()
    name = models.CharField(max_length=255)
    shot_name = models.CharField(max_length=255)
    address = models.CharField(max_length=255, blank=True, null=True)
    email = models.CharField(max_length=255, blank=True, null=True)
    post = models.CharField(max_length=255, blank=True, null=True)
    unp = models.CharField(max_length=255, blank=True, null=True)

    objects = models.Manager()

    def __str__(self) -> str:
        return str(self.number) + " " + self.shot_name


class CIC(models.Model):
    imnss = models.ForeignKey(Imns, on_delete=models.PROTECT)
    number = models.CharField(max_length=255, blank=True, null=True)
    date_state = models.DateField()
    date_from = models.DateField()
    date_to = models.DateField()
    message = models.CharField(max_length=255, blank=True, null=True)

    objects = models.Manager()

    def __str__(self) -> str:
        return "id:" + str(self.id)


class Examination(models.Model):
    obj = models.ForeignKey(Imns, on_delete=models.PROTECT)
    risk = models.ForeignKey(Risk, on_delete=models.PROTECT)
    cic = models.ForeignKey(CIC, on_delete=models.PROTECT)
    department = models.ForeignKey(Department, on_delete=models.PROTECT)
    count_all = models.IntegerField()
    count_contravention = models.IntegerField()
    description = models.TextField(blank=True, null=True)
    fio = models.CharField(max_length=100, blank=True, null=True)

    objects = models.Manager()

    def __str__(self) -> str:
        return "id:" + str(self.id)

dj/tvk/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Sum
from datetime import datetime
from .models import Department, Risk, Imns, CIC, Examination
from .forms import DepartmentsForm, RiskForm, IMNSForm, CICForm,\
    UploadRiskFileForm, ExaminationForm, FilterMainForm
from .function import handle_upload_file, update_risk


# Create your views here.
@login_required
def main(request: HttpRequest, page: int = 1):
    """main"""
    user = request.user

    mainform = FilterMainForm()
    if user.access != 1 and user.access != 3 and user.access != 5:
        mainform.fields['obj'].queryset = Imns.objects.filter(id=user.imns.id)
        mainform.fields['subject'].queryset = Imns.objects.filter(id=user.imns.id)

    subject = ''
    year = datetime.now().year
    if 'subject' in request.GET:
        mainform = FilterMainForm(data=request.GET)
        subject = mainform['subject'].value()
        year = mainform['year'].value()

    if user.access == 1 or user.access == 3 or user.access == 5:
        if subject != '':
            cic_list = CIC.objects.filter(imnss__pk=subject, date_state__year=year).order_by('-id')
        else:
            cic_list = CIC.objects.filter(date_state__year=year).order_by('-id')
    else:
        cic_list = CIC.objects.filter(imnss=user.imns.id, date_state__year=year).order_by('-id')

    cic_rez = []
    for i_cic in cic_list:
        exam_list = Examination.objects.filter(cic=i_cic.id)

        sum_all = exam_list.aggregate(Sum('count_all'))
        i_cic.sum_all = sum_all['count_all__sum'] if sum_all['count_all__sum'] else 0
        sum_cont = exam_list.aggregate(Sum('count_contravention'))
        i_cic.sum_cont = sum_cont['count_contravention__sum'] if sum_cont['count_contravention__sum'] else 0

        obj_list_buf = exam_list.values('obj').distinct()
        obj_list = []
        for i_obj in obj_list_buf:
            obj_list.append(Imns.objects.get(id=i_obj['obj']))
        i_cic.obj_list = obj_list
        risk_list_buf = exam_list.values('risk').distinct()
        risk_list = []
        for i_risk in risk_list_buf:
            risk_list.append(Risk.objects.get(id=i_risk['risk']))
        i_cic.risk_list = risk_list

        dep_list_buf = exam_list.values('department').distinct()
        dep_list = []
        for i_dep in dep_list_buf:
            dep_list.append(Department.objects.get(id=i_dep['department']))
        i_cic.dep_list = dep_list

        i_cic.exam_list = exam_list
        cic_rez.append(i_cic)

    paginator = Paginator(cic_rez, 20)
    page_obj = paginator.get_page(page)

    context = {'page_obj': page_obj,
               'form': mainform}
    return render(request, 'tvk/main.html', context=context)


@login_required
def cic(request: HttpRequest, id: int = None):
    """cic"""
    user = request.user

    cic_form = CICForm()

    if id:
        cic = CIC.objects.get(id=id)
        cic_form = CICForm(instance=cic)

    if user.access == 2 or user.access == 4:
        cic_form.fields['imnss'].queryset = Imns.objects.filter(id=user.imns.id)

    context = {'form': cic_form}

    return render(request, 'tvk/cic.html', context=context)


@login_required
def save_cic(request: HttpRequest):
    """save_cic"""
    if request.method == "POST":
        id = request.POST.get('id', '')
        if id != '':
            cic = CIC.objects.get(id=id)
            cic_form = CICForm(instance=cic, data=request.POST)
        else:
            cic_form = CICForm(data=request.POST)
        if cic_form.is_valid():
            cic_form.save()
        else:
            return HttpResponse(str(cic_form.errors))
    return redirect('tvk:main')


@login_required
def view_cic(request: HttpRequest, id: int):
    """view_cic"""
    if id:

        cic = CIC.objects.get(id=id)
        exam_list = Examination.objects.filter(cic=cic)

        context = {'cic': cic,
                   'exam_list': exam_list}

        return render(request, 'tvk/view_cic.html', context=context)
    return redirect('tvk:main')


@login_required
def delete_cic(request: HttpRequest, id: int):
    """delete_cic"""
    if id:
        cic = CIC.objects.get(id=id)
        exam_list = Examination.objects.filter(cic=cic)
        for i_exam in exam_list:
            i_exam.delete()
        cic.delete()
    return redirect('tvk:main')


@login_required
def department(request: HttpRequest, id: int = None):
    """department"""
    dep_form = DepartmentsForm()
    department_list = Department.objects.all()

    if id:
        dep_form = DepartmentsForm(instance=Department.objects.get(id=id))

    context = {'form': dep_form,
               'department_list': department_list}

    return render(request, 'tvk/departments.html', context=context)


@login_required
def save_department(request: HttpRequest):
    """save_department"""
    if request.method == 'POST':
        dep_form = DepartmentsForm(data=request.POST)
        if request.POST.get('id') != '':
            department = Department.objects.get(id=request.POST.get('id'))
            dep_form = DepartmentsForm(data=request.POST, instance=department)
        if dep_form.is_valid():
            dep_form.save()
        else:
            return HttpResponse(str(dep_form.errors))
    return redirect('tvk:department')


@login_required
def delete_department(request: HttpRequest, id: int = None):
    """delete_deparment"""
    if id:
        department = Department.objects.get(id=id)
        department.delete()
    return redirect('tvk:department')


@login_required
def risk(request: HttpRequest, id: int = None):
    """risk"""
    risk_form = RiskForm()
    file_form = UploadRiskFileForm()

    risk_list = Risk.objects.order_by('-enable', 'code')

    if id:
        risk = Risk.objects.get(id=id)
        risk_form = RiskForm(instance=risk)

    context = {'form': risk_form,
               'file_form': file_form,
               'risk_list': risk_list}

    return render(request, 'tvk/risk.html', context=context)


@login_required
def save_risk(request: HttpRequest):
    """save_risk"""
    if request.method == 'POST':
        id = request.POST.get('id', '')
        if id != '':
            risk = Risk.objects.get(id=id)
            risk_form = RiskForm(data=request.POST, instance=risk)
        else:
            risk_form = RiskForm(data=request.POST)
        if risk_form.is_valid():
            risk_form.save()
        else:
            return HttpResponse(str(risk_form.errors))

    return redirect('tvk:risk')


@login_required
def delete_risk(request: HttpRequest, id: int = None):
    """delete risk"""
    if id:
        risk = Risk.objects.get(id=id)
        risk.delete()
    return redirect('tvk:risk')


@login_required
def upload_file(request: HttpRequest):
    """upload file"""
    if request.method == 'POST':
        file_form = UploadRiskFileForm(request.POST, request.FILES)
        if file_form.is_valid():
            list = handle_upload_file(request.FILES['file'])
            if list:
                update_risk(list)
        else:
            return HttpResponse(str(file_form.errors))
    return redirect('tvk:risk')


@login_required
def imns(request: HttpRequest, id: int = None):
    """imns"""
    imns_form = IMNSForm()

    imns_list = Imns.objects.order_by('number')

    if id:
        imns = Imns.objects.get(id=id)
        imns_form = IMNSForm(instance=imns)

    context = {'form': imns_form,
               'imns_list': imns_list}
    return render(request, 'tvk/imns.html', context=context)


@login_required
def save_imns(request: HttpRequest):
    """save_imns"""
    if request.method == 'POST':
        imns_form = IMNSForm()
        id = request.POST.get('id', '')
        if id != '':
            imns = Imns.objects.get(id=id)
            imns_form = IMNSForm(data=request.POST, instance=imns)
        else:
            imns_form = IMNSForm(data=request.POST)
        if imns_form.is_valid:
            imns_form.save()
        else:
            return HttpResponse(str(imns_form.errors))
    return redirect('tvk:imns')


@login_required
def delete_imns(request: HttpRequest, id: int = None):
    """delete_imns"""
    if id:
        imns = Imns.objects.get(id=id)
        imns.delete()
    return redirect('tvk:imns')


@login_required
def exam(request: HttpRequest, cic: int, id: int = None):
    """exam"""
    form = ExaminationForm()

    user = request.user
    if user.access != 1:
        form.fields['obj'].queryset = Imns.objects.filter(id=user.imns.id)

    if id:
        exam = Examination.objects.get(id=id)
        form.fields['id'].initial = exam.id
        form.fields['obj'].initial = exam.obj
        form.fields['cic'].initial = cic
        form.fields['risk'].initial = exam.risk
        form.fields['department'].initial = exam.department
        form.fields['count_all'].initial = exam.count_all
        form.fields['count_contravention'].initial = exam.count_contravention
        form.fields['description'].initial = exam.description
    else:
        form.fields['cic'].initial = cic

    exam_list = Examination.objects.filter(cic=CIC.objects.get(id=cic))

    context = {'form': form,
               'exam_list': exam_list}

    return render(request, 'tvk/exam.html', context=context)


@login_required
def save_exam(request: HttpRequest):
    """save_exam"""
    if request.method == 'POST':
        id = request.POST.get('id', '')
        obj = request.POST.get('obj')
        risk = request.POST.get('risk')
        cic = request.POST.get('cic')
        dep = request.POST.get('department')
        count_all = request.POST.get('count_all')
        count_contravention = request.POST.get('count_contravention')
        description = request.POST.get('description')
        fio = request.POST.get('fio')

        exam = Examination()
        if id != '':

dj/tvk/templates/tvk/base_generic.html
<!DOCTYPE html>
<html lang='en'>
{% load static %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="TVK">
  <meta name="author" content="Anton Kralin">
  <title>TVK</title>
  <link href="{%static 'tvk/css/bootstrap.min.css'%}" rel="stylesheet">
  <link href="{%static 'tvk/css/my.css'%}" rel="stylesheet">
</head>

<body style='padding-bottom:55px'>
    <div class="p-1"> 
        {% block content %}{% endblock %}
    </div>

    {%block footer %}
    <nav class="navbar fixed-bottom navbar-expand-sm navbar-dark bg-dark"> 
        <div class="container-fluid"> 
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <a class="navbar-brand" href="{%url 'tvk:main'%}">Главная</a>
                {% if user.access < 5 %}
                    <a class="navbar-brand" href="{%url 'tvk:cic' %}">Создать ТВК</a>
                {% endif %}
                <li class="nav-item dropup">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown10" data-bs-toggle="dropdown" aria-expanded="false">Отчеты</a>
                    <ul class="dropdown-menu" aria-labelledby="dropdown10">
                        <li><a class="dropdown-item" href="{% url 'report:choose_period' %}">Сводный отчет</a></li>
                        <li><a class="dropdown-item" href="{% url 'report:contraventions' %}">Отчет по нарушениям</a></li>
                        <li><a class="dropdown-item" href="{% url 'report:checking' %}">Отчет по проверкам</a></li>
                    </ul>
                </li>
            </ul>

            <form class="d-flex">
                <ul class="navbar-nav">
                    {% if user.access < 3 %}
                    <li class="nav-item dropup">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown10" data-bs-toggle="dropdown" aria-expanded="false">Управление</a>
                        <ul class="dropdown-menu" aria-labelledby="dropdown10">
                            <li><a class="dropdown-item" href="{%url 'users:users'%}">Пользователь</a></li>
                            {% if user.access == 1 %}
                                <li><a class="dropdown-item" href="{%url 'tvk:department' %}">Подразделения</a></li>
                                <li><a class="dropdown-item" href="{%url 'tvk:imns' %}">Инспекции</a></li>
                                <li><a class="dropdown-item" href="{%url 'tvk:risk' %}">Риски</a></li>
                            {% endif %}
                        </ul>
                    </li>
                    {% endif %}
                
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">{{user.username}}</a>
                    </li> 
                <a class="navbar-brand" aria-current="page" href="{% url 'users:clearsession' %}">Выход</a>
            </form>
        </div>
    </nav>
    {% endblock %}

    <script src="{% static 'tvk/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

dj/tvk/templates/tvk/choose_period.html
{% extends 'tvk/base_generic.html' %}

{% block content %}
    <div class='container'>
        <form action="{% url 'tvk:report' %}" method='POST'>
            {% csrf_token %}
            <table>
                {{form.as_table}}
            </table>
            <input type='submit' value='Сформировать' />
        </form>
    </div>
{% endblock %}

dj/tvk/templates/tvk/cic.html
{% extends 'tvk/base_generic.html' %}

{% block content %}
    <div class='container-fluid'>
    <div class='row'>
        <form action='{%url "tvk:save_cic"%}' method='POST'>
            {% csrf_token %}
            {{form.as_p}}
            <input type='submit' value='Сохранить' />
            <p></p>
            <br>
            <br>
        </form>

        <div class='col-10'>
            {% if form.id.value != ''%}
                <a href="{%url 'tvk:exam' cic=form.id.value %}" >Проверки</a>
            {% endif %}
        </div>
        <div class='col-2'>
            {% if user.access == 1 and form.id.value != '' %}
                <a href="{%url 'tvk:delete_cic' id=form.id.value %}" onclick="return confirm('Вы уверены что хотите удалить?');">Удалить</a>
            {% endif %}
        </div>
    </div>
    </div>
{% endblock %}

dj/tvk/templates/tvk/departments.html
{% extends 'tvk/base_generic.html' %}

{% block  content %}
    <div class='container-fluid'>
    <div class='row'>
        <div class='col-6'>
            <div class="table-responsive">
                <table class="table table-striped table-bordered w-auto">
                    <thead>
                        <th>№</th>
                        <th>Название</th>
                        <th></th>
                        <th></th>
                    </thead>
                    <tbody>
                        {% for i_department in department_list.all %}
                            <tr>
                                <td>{{i_department.id}}</td>
                                <td>{{i_department.name}}</td>
                                <td><a href={% url 'tvk:edit_department' id=i_department.id %}>Изменить</a></td>
                                <td><a href={% url 'tvk:delete_department' id=i_department.id %}>Удалить</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <div class='col-6'>
            <form action='{% url "tvk:save_department" %}' method='POST'>
                {% csrf_token %}
                {{form.as_p}}
                <input type='submit' value='Сохранить' />
            </form>
        </div>
    </div>
    </div>
{% endblock %}

dj/tvk/templates/tvk/exam.html
{% extends 'tvk/base_generic.html' %}

{% block content %}
    <div class='container-fluid'>
    <div class='row'>
        <div class='col-6'>
            <div class="table-responsive">
                <table class="table table-striped table-bordered w-auto">
                    <thead>
                        <th>Объект</th>
                        <th>Риск</th>
                        <th>Подразделение</th>
                        <th>Количество документов</th>
                        <th>Количество нарушений</th>
                        <th>ФИО</td>
                        <th></th>
                        <th></th>
                    </thead>
                    <tbody>
                        {%for i_exam in exam_list %}
                            <tr title='{{i_exam.description}}'>
                                <td>{{i_exam.obj.number}}</td>
                                <td>{{i_exam.risk.code}}</td>
                                <td>{{i_exam.department.name}}</td>
                                <td>{{i_exam.count_all}}</td>
                                <td>{{i_exam.count_contravention}}</td>
                                <td>{{i_exam.fio}}</td>
                                <td><a href="{% url 'tvk:edit_exam' cic=i_exam.cic.id id=i_exam.id %}">Изменить</a></td>
                                <td><a href="{% url 'tvk:delete_exam' id=i_exam.id %}">Удалить</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <div class='col-6'>
            <form action="{%url 'tvk:save_exam'%}" method='POST'>
                {% csrf_token %}
                {{form.as_p}}
                <input type='submit' value='Сохранить' />
            </form>
        </div>
    </div>
    </div>
{% endblock %}

dj/tvk/templates/tvk/imns.html
{% extends 'tvk/base_generic.html' %}

{% block content %}
    <div class='container-fluid'>
    <div class='row'>
        <div class='col-6'>
            <div class="table-responsive">
                <table class="table table-striped table-bordered w-auto">
                    <thead>
                        <th>Номер</th>
                        <th>Название</th>
                        <th>УНП</th>
                        <th>Email</th>
                        <th></th>
                        <th></th>
                    </thead>
                    <tbody>
                        {% for i_imns in imns_list.all %}
                            <tr>
                                <td title='{{i_imns.address}}'>{{i_imns.number}}</td>
                                <td title='{{i_imns.name}}'>{{i_imns.shot_name}}</td>
                                <td title='{{i_imns.post}}'>{{i_imns.unp}}</td>
                                <td title='{{i_imns.post}}'>{{i_imns.email}}</td>
                                <td><a href="{%url 'tvk:edit_imns' id=i_imns.id%}">Изменить</a></td>
                                <td><a href="{%url 'tvk:delete_imns' id=i_imns.id%}">Удалить</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <div class='col-6'>
            <form action='{%url "tvk:save_imns" %}' method='POST'>
                {% csrf_token %}
                {{form.as_p}}
                <input type='submit' value='Сохранить' />
            </form>
        </div>
    </div>
    </div>
{% endblock %}

dj/tvk/templates/tvk/main.html
{% extends 'tvk/base_generic.html' %}

{% block content %}
<div class='container-fluid'>
    <div class='row'>
        <form action="{% url 'tvk:main'%}" method='GET' name='main_form'>
            {% csrf_token %}
            {{form}}
        </form>

        <div class="table-responsive">
            <table class="table table-striped table-bordered w-auto">
                <thead>
                        <th>№</th>
                        <th>Субъект</th>
                        <th>Объекты контроля</th>
                        <th>№ отчета</th>
                        <th>Дата утверждения</th>
                        <th>Дата с-по</th>
                        <th>Риски</th>
                        <th>Всего документов</th>
                        <th>Всего нарушений</th>
                        <th>Управление</th>
                        <th></th>
                        <th></th>
                </thead>
                <tbody>
                    {% for i_cic in page_obj %}
                        <tr>
                            <td>{{i_cic.id}}</td>
                            <td>{{i_cic.imnss.number}}</td>
                            <td>
                                {% for i_obj in i_cic.obj_list%}
                                    {{i_obj.number}};
                                {% endfor %}
                            </td>
                            <td>{{i_cic.number}}</td>
                            <td>{{i_cic.date_state|date:'d.m.Y'}}</td>
                            <td>{{i_cic.date_from|date:'d.m.Y'}} - {{i_cic.date_to|date:'d.m.Y'}}</td>
                            <td>
                                {% for i_risk in i_cic.risk_list %}
                                    {{i_risk.code}}; 
                                {% endfor %}
                            </td>
                            <td>{{i_cic.sum_all}}</td>
                            <td>{{i_cic.sum_cont}}</td>
                            <td>{% for i_dep in i_cic.dep_list %}{{i_dep.name}}; {%endfor%}</td>
                            <td>
                                {% if user.access < 5%}
                                    <a href="{%url 'tvk:edit_cic' id=i_cic.id%}">✎</a>
                                {% endif %}
                            </td>
                            <td><a href="{%url 'tvk:view_cic' id=i_cic.id%}">🔎</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% block paginator %}
                <div class='pagination'>
                    <span class='page-links'>
                        {% if page_obj.has_previous %}
                            <a href="{% url 'tvk:p_main' page=page_obj.previous_page_number%}">Предыдущая</a>
                            {% endif %}
                            <span class="page-current">
                                Страница {{page_obj.number}} из {{page_obj.paginator.num_pages}}.
                            </span>
                            {% if page_obj.has_next%}
                            <a href="{% url 'tvk:p_main' page=page_obj.next_page_number%}">Следующая</a>
                        {% endif %}
                        {% for page_number in page_obj.paginator.page_range %}
                            <a
                                href="{% url 'tvk:p_main' page=page_number%}"
                                class="{% if page_number == page_obj.number %}current{% endif %}"
                            >
                                {{page_number}}
                            </a>
                        {% endfor %}
                    </span>
                </div>
            {% endblock %}
    </div>
</div>
{% endblock %}

dj/tvk/templates/tvk/risk.html
{% extends 'tvk/base_generic.html' %}

{% block content %}

    <div class='container-fluid'>
    <div class='row'>
        <div class='col-6'>
            <div class="table-responsive">
                <table class="table table-striped table-bordered w-auto">
                    <thead>
                        <th>Код риска</th>
                        <th>Название риска</th>
                        <th>Статус</th>
                        <th></th>
                        <th></th>
                    </thead>
                    <tbody>
                        {% for i_risk in risk_list.all %}
                            <tr>
                                <td title='{{i_risk.description}}'>{{i_risk.code}}</td>
                                <td title='{{i_risk.description}}'>{{i_risk.name}}</td>
                                <td title='{{i_risk.description}}'>{{i_risk.enable}}</td>
                                <td><a href="{%url 'tvk:edit_risk' id=i_risk.id%}">Изменить</a></td>
                                <td><a href="{%url 'tvk:delete_risk' id=i_risk.id%}">Удалить</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <br>
                <br>
            </div>
        </div>

        <div class='col-6'>
            <form action='{% url "tvk:save_risk" %}' method='POST'>
                {% csrf_token %}
                {{form.as_p}}
                <input type='submit' value='Сохранить' />
            </form>
            <div>
                <p></p>
                <p class="text-center">Для загрузки необходим файл *.csv в кодировке UTF-8, в котором будут 2 столбца(без заголовка/шапки): код риска и название</p>
                <p class="text-center">Разделитель полей - ;</p>
                <form action="{% url 'tvk:upload_file'%}" enctype="multipart/form-data" method='POST'>
                    {% csrf_token %}
                    {{file_form.as_p}}
                    <input type='submit' value='Загрузить' />
                </form>
            </div>
        </div>
    </div>
    </div>
{% endblock %}